# Introduction
- Trong phần này, ta sẽ học về QR decomposition và một loại ma trận mới (orthogonal matrix). 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Orthogonal Matrices 

- Orthogonal matrix (ma trận trực giao) là ma trận thỏa mãn tính chất sau : 
    1. Mỗi cột khác nhau đều trực giao (dot product = 0)
    2. Mỗi cột có norm chính xác bằng 1 
- Miêu tả biểu thức : $$ <q_i, q_j>= \begin{cases} 0 &\text{if i != j } \\ 1 &\text{if i = j} \end{cases}  $$
- Dựa vào đây ta có thể suy ra tính chất của ma trận trực giao đó là tích giữa ma trận đó và chuyển vị của nó là I. ($ Q^TQ = I = QQ^T$)

In [3]:
Q1 = np.array([
    [1, -1], [1, 1]
])

Q2 = np.array([
    [1, 2, 2], [2, 1, -2], [-2, 2, -1]
])
print(Q1.T @ Q1)
print(Q2 @ Q2.T)

[[2 0]
 [0 2]]
[[9 0 0]
 [0 9 0]
 [0 0 9]]


- Một số tính chất của ma trận trực giao : 
    1. Ma trận hoán vị (Permutation matrices) là một ma trận trực giao 
    2. Pure rotation (xoay không làm thay đổi chiều dài của vector) là phép nhân với ma trận trực giao 
- Ma trận trực giao có thể được tính từ một ma trận không trực giao từ QR decomposition, cái mà đơn gian là một phiên bản phức tạp hơn của Gram-Schmidt

# Gram-Schmidt 
- 