# Row reduction and LU decomposition

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

## 1. Systems of Equation 
- Hệ phương trình là tập các phương trình có mối quan hệ với nhau 
- Cách tiếp cận giải hệ phương trình đó là nhân vô hướng hai vế của phương trình và trừ chúng đi lẫn nhau

### Converting equations into Matrices 
- Có thể chuyển đổi một hệ phương trình thành một matrix cho việc tìm nghiệm. Thay đổi với 2 bước : 
    1. chia đẳng thức thành constant ở bên phải và chứa biến ở bên trái $$ \begin{cases} x + y = 4 \\ - \frac{x}{2} + y = 2 \end{cases} $$ 
    2. Với vế trái, tách các hệ số (coeficients) thành một matrix với một row mỗi hệ số đó, vector biến được đặt theo chiều dọc và kết quả. Đẳng thức sẽ được chuyển thành phép toán có dạng : $$ Ax = b $$ 


### Working with Matrix Equations 
- Ta có thể sử dụng matrix equation tương tự như với các đẳng thức thông thường (phép norm, adding, multiplying, transposing, .... )
- Điều khác biết khi sử dụng các đẳng thức ma trận đó là phép nhân ma trận phụ thuộc vào chiều (side-dependent), phải nhân cùng một chiều với cả 2 bên đẳng thức 
$$ AX = B \\  CAX = CB $$ 

In [2]:
# ví dụ về giải bài toán chiều của matrix 
A = np.random.randn(4, 4)
B = np.random.randn(4, 4)

X1 = np.linalg.inv(A) @ B 
X2 = B @ np.linalg.inv(A)

In [3]:
res1 = A @ X1 - B 
res1 

array([[-1.11022302e-16,  5.55111512e-17,  0.00000000e+00,
         2.22044605e-16],
       [ 5.55111512e-17,  0.00000000e+00,  0.00000000e+00,
        -2.22044605e-16],
       [-4.44089210e-16,  0.00000000e+00, -5.55111512e-17,
         0.00000000e+00],
       [-8.32667268e-17,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

In [4]:
res2 = A@X2 - B
res2

array([[-1.06149943,  1.85941999,  3.24201534,  0.09024697],
       [-0.49302033,  0.3704671 , -1.49037043, -2.73280127],
       [ 6.07783223,  0.26248483,  1.77604857, -0.64761456],
       [ 0.00805797, -0.98327359,  2.27186999, -1.08501623]])

=> Có thể thấy, với hai các nhân khác nhau, matrix kết quả khác nhau

## 2. Row reduction 
- Row reduction là quá trình thực hiện hai phép toán : nhân vô hướng và cộng các hàng của matrix. 
- Mục tiêu chính của row reduction đó là chuyển đổi ma trận dày (dense matrix) thành một matrix tam giá trên (kết quả được gọi là echelon form).
- Ma trận sau khi được giảm chiều khác với ma trận trước khi giảm chiều,  nhưng hai ma trận được link với nhau bởi một ma trận tuy
- Người ta thường gọi ma trận link đó là $ L^{-1} $ hay trong LU decomposition có : $$ A = LU $$ với U là một matrix upper triangular và L là một transform matrix.
- Thông qua việc nhân vô hướng, có thể thấy có vô số U (echelon form)



In [5]:
def first_col_zeros(A: np.array) : 
    B = np.copy(A)

    for i in range(1, len(B)): 
        B[i] = B[i] - (B[i, 0]  /  B[0, 0]) * B[0]

    return B

reduced_matrix = first_col_zeros(A)
print(reduced_matrix)

[[-2.06212441e+00 -3.42423110e-02 -9.50522660e-01  5.66040696e-01]
 [ 0.00000000e+00  1.56886657e+00 -1.64343002e-01  5.66941719e-01]
 [ 0.00000000e+00  1.08157662e-03  2.97781428e+00  6.07665527e-02]
 [ 0.00000000e+00  4.59662727e-01  1.22501611e-01 -1.12028897e+00]]


### Gaussian Elimination 
- Kĩ thuật khử Gaussian có thể giải được một phương trình matrix tuyến tính mà không cần tính inverse matrix.  
- Kĩ thuật này biến đổi matrix hệ số về dạng echelon form. Từ đó giải từng nghiệm của bài toán và thế ngược lại vào nghiệm trên